(defpackage :sdl2.iolib (:use :cl))
(in-package :sdl2.iolib)

(ql:quickload '(:sdl2 :iolib))

(defun test ()
  (sdl2:with-everything (:window w :gl g)
    (let ((i 0))
      (sdl2:with-sdl-event (event)
        (iolib:with-event-base (event-base)
          (flet ((update ()
                   (when (> (incf i) 2000)
                     (iolib:exit-event-loop event-base))
                   (sdl2:pump-events)
                   (print (sdl2:mouse-state))
                   ;; (loop for e = (sdl2::sdl-poll-event event)
                   ;;       for p = (= e 0)
                   ;;       until p
                   ;;       do (let ((type (sdl2:get-event-type event)))
                   ;;            (print (incf i))                            
                   ;;            (print type)
                   ;;            (when (eq type :quit)
                   ;;              (iolib:exit-event-loop event-base))))
                   (finish-output)))
            (iolib:add-timer event-base #'update 0.1)
            (iolib:event-dispatch event-base)))))))
